service: solicitud # NOTE: update this with your service name

plugins:
  - serverless-step-functions

provider:
  name: aws
  runtime: nodejs6.10
  memorySize: 128
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:us-east-1:255410818070:table/Inventario"

    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:us-east-1:255410818070:table/Bodega"

    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:us-east-1:255410818070:table/SolicitudAbastecimiento"

    - Effect: Allow
      Action:
        - sns:publish
      Resource: "arn:aws:sns:us-east-1:255410818070:enviarCorreo"

functions:
  stepBuscarBodegas:
    handler: Steps/encontrarCandidatos.postularBodegas

  stepDarDistanciasUbicacionPedido:
    handler: Steps/calcularDistancias.darDistancias

  stepCrearSolicitudes:
    handler: Steps/crearSolicitudes.generar

  enviarCorreo:
    handler: Steps/enviarCorreo.enviar

stepFunctions:
  stateMachines:
    procesarSolicitudPedido:
      StartAt: buscarBodegasConInventario
      States:
        buscarBodegasConInventario:
          Type: Task
          Resource: stepBuscarBodegas
          Catch:
          - ErrorEquals:
            - States.ALL
            Next: enviarCorreo
          Next: calcularDistancias
        calcularDistancias:
          Type: Task
          Resource: stepDarDistanciasUbicacionPedido
          Catch:
          - ErrorEquals:
            - States.ALL
            Next: enviarCorreo
          Next: generarSolicitudes
        generarSolicitudes:
          Type: Task
          Resource: stepCrearSolicitudes
          Catch:
          - ErrorEquals:
            - States.ALL
            Next: enviarCorreo
          Next: enviarCorreo
        enviarCorreo:
          Type: Task
          Resource: enviarCorreo
          End: true


